[workspace]
members = ["py"]
default-members = [".", "py"]

[workspace.package]
version = "0.2.3"
edition = "2021"

[workspace.dependencies]
polling = "3"

[package]
name = "loopmini"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Rust-backed asyncio event loop"
repository = "https://github.com/AnswerDotAI/loopmini"

[lib]
name = "loopmini"

[dependencies]
polling.workspace = true

[profile.test]
inherits = "release"

[profile.release]
lto = false
codegen-units = 16

[profile.release.package.loopmini]
incremental = true

[profile.release.package.loopmini-py]
incremental = true

[profile.dist]
inherits = "release"
lto = true
incremental = false
codegen-units = 1
strip = true

[profile.dist.package.loopmini]
incremental = false

[profile.dist.package.loopmini-py]
incremental = false
